# Generated by Django 2.2.6 on 2020-01-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sight', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='photo_sight')),
                ('year', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
