# Generated by Django 2.2.6 on 2020-01-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200114_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
