# Generated by Django 2.2.6 on 2020-01-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_sight_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('V', 'VIP'), ('L', 'Lite')], max_length=1)),
                ('days', models.IntegerField()),
                ('desc', models.TextField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
    ]
