# Generated by Django 2.2.6 on 2020-01-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='desc',
            field=models.TextField(),
        ),
    ]
