# Generated by Django 2.2.6 on 2020-01-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200115_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(choices=[('VIP', 'V'), ('Lite', 'L')], max_length=1),
        ),
    ]
