# Generated by Django 2.2.6 on 2020-01-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200115_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Lite', 'Lite')], max_length=4),
        ),
    ]
