# Generated by Django 2.2.6 on 2020-01-18 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200115_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='type_slug',
            field=models.SlugField(default='lite or vip'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_person', models.CharField(max_length=20)),
                ('surname_person', models.CharField(max_length=20)),
                ('date_start', models.DateField()),
                ('type_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Type')),
            ],
        ),
    ]
